name: PHPStan

on:
  push:
    branches:
      - "develop"
      - "3.x-develop"
  pull_request:
    branches:
      - "develop"
      - "3.x-develop"

jobs:
  phpstan:
    name: Static Analysis
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410b181273ba90b1 # v7.0.1
      - id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-8.4-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-8.4-
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 8.4
          extensions: bcmath, cli, curl, gd, mbstring, mysql, openssl, pdo, tokenizer, xml, zip
          tools: composer:v2
          coverage: none
      - run: cp .env.ci .env
      - run: composer install --no-interaction --no-progress --no-suggest --prefer-dist
      - run: vendor/bin/phpstan analyse --no-progress --memory-limit=1G
