name: TSC

on:
  push:
    branches:
      - "develop"
      - "3.x-develop"
  pull_request:
    branches:
      - "develop"
      - "3.x-develop"

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-24.04
    steps:
      - name: Code checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410b181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@ff378ebe6b225b0680b81c1ad4498ae0d1d3a5e3 # v6.0.10

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck
